---
applications:
- name: order-service-cf
  memory: 1G
  instances: 1
  buildpacks:
    - java_buildpack_offline
  env:
    DT_CUSTOM_PROP: DEPLOYMENT_GRP_NME=ORDER-SERVICE-DTGRP DEPLOYMENT_COLOR=ORDER-SERVICE-APPCOLOR
    DEPLOYMENT_GRP_NME: ORDER-SERVICE-DTGRP    
    incrementthistoforcenewrelease: 24
    CATALOG_SERVICE_HOST: 35.188.70.99
    CATALOG_SERVICE_PORT: 8080
    CUSTOMER_SERVICE_HOST: 35.226.106.233
    CUSTOMER_SERVICE_PORT: 8080
