---
applications:
- name: order-service-cf
  memory: 1G
  instances: 1
  buildpacks:
    - java_buildpack_offline
  env:
    DT_CUSTOM_PROP: DEPLOYMENT_GRP_NME=ORDER-SERVICE-DTGRP DEPLOYMENT_COLOR=ORDER-SERVICE-APPCOLOR
    DEPLOYMENT_GRP_NME: ORDER-SERVICE-DTGRP    
    incrementthistoforcenewrelease: 7
    CATALOG_SERVICE_HOST: a5637134d519911e9a9ca026a2a01533-1050313695.us-east-2.elb.amazonaws.com
    CATALOG_SERVICE_PORT: 8080
    CUSTOMER_SERVICE_HOST: a52142863519911e9a9ca026a2a01533-1600858474.us-east-2.elb.amazonaws.com
    CUSTOMER_SERVICE_PORT: 8080
